### ISSUE TITLE
can_delete

### ISSUE THREAD

**Issue by cord** [optimistdigital/nova-notes-field#11]
good stuff!

From the code, I see the delete link is only displayed when `can_delete` is true. 

How can we control if a user note can be deleted?

**Comment by Tarpsvo** [comment]
Hi! I added a new feature for that in version 1.5.0. It requires defining a new `Gate` where you can return either true or false.

See the documentation: https://github.com/optimistdigital/nova-notes-field#custom-delete-authorization
