### ISSUE TITLE
No name appears as user posts

### ISSUE THREAD

**Issue by LorenzoSapora** [optimistdigital/nova-notes-field#23]
Is it looking for the column `users.name`? I don't have that column, but even with an

```php
    public function getNameAttribute()
    {
        return "{$this->first_name} {$this->last_name}";
    }
```
it doesn't seem to make a difference. I'm definitely missing something here, but can't put my finger on what.

![image](https://user-images.githubusercontent.com/25519274/100399026-0c2db500-3049-11eb-9a0e-648720d7dc5b.png)

**Comment by Tarpsvo** [comment]
Hey @LorenzoSapora!

I improved the name logic a bit, it should work for you now, even without the `getNameAttribute()` in version 1.5.8.

You were very close to a workaround - only thing missing was a `protected $appends = ['name'];`. Now it should work out of the box though.

Thanks for reporting this!
