### ISSUE TITLE
Adding a note triggers a resource update

### ISSUE THREAD

**Issue by tmartty** [optimistdigital/nova-notes-field#24]
If I'm on the edit view on my resource and add a note, when I hit 'Add note', after saving the new note a resource update is somehow triggered and a POST is made, which then redirects the user out of the edit view and onto the details/default view of the resource.

**Comment by Tarpsvo** [comment]
Ah yes, could be due to the <button> type. I'll check this in a second.

**Comment by Tarpsvo** [comment]
That's weird - I can't reproduce this. What version of Nova and nova-notes-field?

**Comment by Tarpsvo** [comment]
Ah yes - reproduces on Firefox. Just a sec.

**Comment by Tarpsvo** [comment]
Hi! Released a fix in version 2.0.0.

A major release because I updated some dependencies and dropped support for old versions of Nova and Laravel.

**Comment by tmartty** [comment]
Ah shoot, I'm using Nova 2.0..

No way to make this fix compatible? :grin:

**Comment by Tarpsvo** [comment]
What's stopping you from upgrading to 3? :S Nova 2 hasn't been updated since March.

**Comment by tmartty** [comment]
Client project using Laravel 6.2... no time to update everything at this stage sadly. :/
