### ISSUE TITLE
Not able to optimise config cache

### ISSUE THREAD

**Issue by SimonBarrettACT** [optimistdigital/nova-notes-field#29]
If the following line is in the config file:

`'get_avatar_url' => fn ($user) => $user->getAvatarUrl(),`

When running:

`php artisan optimize`

A _Your configuration files are not serializable._ error is produced. 

This is caused by using a closure in the config file.

**Comment by Tarpsvo** [comment]
Thanks a ton for the PR! I merged it and released in version 2.0.1. :) Good luck!
