### ISSUE TITLE
Ability to show notes on edit view

### ISSUE THREAD

**Issue by VTumanov** [optimistdigital/nova-notes-field#3]
Good solution, thank your! 

There are scenarios when data operators (when updating the database) do not go to view the record, but immediately edit it. In this case, the operator will not see important comments.

You can add same template like in detail view to edit view? Then users of the module will be able to decide when to show them.

**Comment by Tarpsvo** [comment]
Hey! Still working on getting it to the edit view. I was thinking of adding a button to the top-right to open it in a model and optionally displaying it the same as on the detail view. I will get to it tomorrow.

**Comment by Tarpsvo** [comment]
The notes field is now visible on the edit view as well. Released in version 1.1.0.
