### ISSUE TITLE
Not working on soft deletes

### ISSUE THREAD

**Issue by mateusz-peczkowski** [optimistdigital/nova-notes-field#43]
As I see notes field is not working when a user is soft deleted. It's highly important cause we are making notes about why we are deleting users ;) In that case, we need to make them before we delete resources cause probably there are no ->withTrashed inside your code and when going to the resource we are seeing plain input with covered submit button (not HTML WSYWIG version)... + in dev console I have:
```
/nova-vendor/nova-notes/notes?resourceId=8568&resourceName=investors:1 Failed to load resource: the server responded with a status of 400 (Bad Request)
vendor.js?id=158eb2009eabe0a47c04:1 Uncaught (in promise) Error: Request failed with status code 400
    at FtD3.t.exports (vendor.js?id=158eb2009eabe0a47c04:1)
    at t.exports (vendor.js?id=158eb2009eabe0a47c04:1)
    at XMLHttpRequest.p.onreadystatechange (vendor.js?id=158eb2009eabe0a47c04:1)
```

**Comment by Tarpsvo** [comment]
Hi! Thanks for reporting this issue. I fixed it in the new release, 2.0.3. :) Good luck!
